
/*
 * AnimationForm.java
 *
 * Created on 2010-03-22, 20:36:40
 */

package attragen.gui;

import attragen.core.*;
import java.awt.geom.Point2D;
import java.io.File;
import java.io.IOException;
import java.util.Map;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Rafal
 */
public class AnimationForm extends javax.swing.JFrame {
    private MainForm parentform;

    private Map<String, Object> startData = null;
    private Map<String, Object> endData = null;
    private int count = 250;
    private boolean running = false;

    private Animation anim = new Animation();

    /** Creates new form AnimationForm */
    public AnimationForm() {
        initComponents();

        fcDialog.addChoosableFileFilter(new AttractorFilter());
        tOutputFolder.setText(System.getProperty("user.dir"));
    }

    private void setButtonState() {
        if (startData == null) { bGenerate.setEnabled(false); return; }
        if (endData == null)   { bGenerate.setEnabled(false); return; }

        if (!lData1.getText().equals(lData2.getText())) { bGenerate.setEnabled(false); return; }

        if (count == 0) { bGenerate.setEnabled(false); return; }

        if (tOutputFolder.getText().isEmpty()) { bGenerate.setEnabled(false); return; }
        File folder = new File(tOutputFolder.getText());
        if (!folder.exists()) { bGenerate.setEnabled(false); return; }

        bGenerate.setEnabled(true);
    }

    private void setMaxProgress(int max) {
        count = max;
        lProgress.setText("0 / " + String.valueOf(max));
        pbProgress.setMaximum(max);
    }

    public void setParentForm(MainForm form) {
        parentform = form;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fcDialog = new javax.swing.JFileChooser();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        bLoad1 = new javax.swing.JButton();
        tFramerate = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        bSelectOutput = new javax.swing.JButton();
        lData2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lData1 = new javax.swing.JLabel();
        bAbort = new javax.swing.JButton();
        pbProgress = new javax.swing.JProgressBar();
        lProgress = new javax.swing.JLabel();
        tOutputFolder = new javax.swing.JTextField();
        bGenerate = new javax.swing.JButton();
        bLoad2 = new javax.swing.JButton();
        tDuration = new javax.swing.JFormattedTextField();

        fcDialog.setCurrentDirectory(new File(System.getProperty("user.dir")));

        setTitle("Opcje animacji");
        setResizable(false);

        jLabel5.setText("s");

        jLabel6.setText("Czas trwania:");

        bLoad1.setText("Wczytaj...");
        bLoad1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLoad1ActionPerformed(evt);
            }
        });

        tFramerate.setColumns(2);
        tFramerate.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        tFramerate.setValue(25);
        tFramerate.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tFrameratePropertyChange(evt);
            }
        });

        jLabel7.setText("Ilość klatek na sekundę:");

        jLabel3.setText("Atraktor końcowy:");

        bSelectOutput.setText("Wybierz...");
        bSelectOutput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSelectOutputActionPerformed(evt);
            }
        });

        lData2.setFont(lData2.getFont().deriveFont(lData2.getFont().getStyle() | java.awt.Font.BOLD));
        lData2.setText("<brak>");

        jLabel8.setText("Folder wyjściowy:");

        jLabel1.setText("Atraktor początkowy:");

        lData1.setFont(lData1.getFont().deriveFont(lData1.getFont().getStyle() | java.awt.Font.BOLD));
        lData1.setText("<brak>");

        bAbort.setText("Przerwij");
        bAbort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAbortActionPerformed(evt);
            }
        });

        pbProgress.setMaximum(250);

        lProgress.setText("0 / 250");

        bGenerate.setText("Generuj");
        bGenerate.setEnabled(false);
        bGenerate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bGenerateActionPerformed(evt);
            }
        });

        bLoad2.setText("Wczytaj...");
        bLoad2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLoad2ActionPerformed(evt);
            }
        });

        tDuration.setColumns(3);
        tDuration.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        tDuration.setValue(10);
        tDuration.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tDurationPropertyChange(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                        .addComponent(lData1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bLoad1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 257, Short.MAX_VALUE)
                        .addComponent(tDuration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 225, Short.MAX_VALUE)
                        .addComponent(tFramerate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 140, Short.MAX_VALUE)
                                .addComponent(lData2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tOutputFolder, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bLoad2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bSelectOutput, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bGenerate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bAbort)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addComponent(lProgress)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pbProgress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bLoad1)
                    .addComponent(jLabel1)
                    .addComponent(lData1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bLoad2)
                    .addComponent(jLabel3)
                    .addComponent(lData2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tDuration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tFramerate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bSelectOutput)
                    .addComponent(jLabel8)
                    .addComponent(tOutputFolder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pbProgress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bGenerate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lProgress)
                        .addComponent(bAbort)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bLoad1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLoad1ActionPerformed
        fcDialog.setDialogTitle("Wczytaj atraktor początkowy");

        int result = fcDialog.showOpenDialog(this);

        if (result == JFileChooser.APPROVE_OPTION) {
            File f = fcDialog.getSelectedFile();

            try {
                startData = DataHandler.load(f);
                
                lData1.setText((String)startData.get("formula"));

                setButtonState();
            } catch (IOException e) {
                JOptionPane.showMessageDialog(this, "Nie można było otworzyć pliku.", this.getTitle(), JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_bLoad1ActionPerformed

    private void bLoad2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLoad2ActionPerformed
        fcDialog.setDialogTitle("Wczytaj atraktor końcowy");

        int result = fcDialog.showOpenDialog(this);

        if (result == JFileChooser.APPROVE_OPTION) {
            File f = fcDialog.getSelectedFile();

            try {
                endData = DataHandler.load(f);
                
                lData2.setText((String)endData.get("formula"));

                setButtonState();
            } catch (IOException e) {
                JOptionPane.showMessageDialog(this, "Nie można było otworzyć pliku.", this.getTitle(), JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_bLoad2ActionPerformed

    private void tFrameratePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tFrameratePropertyChange
        if (evt.getPropertyName().equals("value")) {
            if (evt.getNewValue() != null) {
                int framerate = ((Number)evt.getNewValue()).intValue();
                int duration = ((Number)tDuration.getValue()).intValue();
                setMaxProgress(duration * framerate);
                setButtonState();
            }
        }
    }//GEN-LAST:event_tFrameratePropertyChange

    private void tDurationPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tDurationPropertyChange
        if (evt.getPropertyName().equals("value")) {
            if (evt.getNewValue() != null) {
                int duration = ((Number)evt.getNewValue()).intValue();
                int framerate = ((Number)tFramerate.getValue()).intValue();
                setMaxProgress(duration * framerate);
                setButtonState();
            }
        }
    }//GEN-LAST:event_tDurationPropertyChange

    private void bGenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGenerateActionPerformed
        if (parentform.gen.isRunning()) return;

        // OMGWTF^2
        Double[] startbig = (Double[])startData.get("params");
        Double[] endbig = (Double[])endData.get("params");
        double[] start = new double[startbig.length];
        double[] end = new double[endbig.length];
        for (int i=0; i<start.length; i++) {
            start[i] = startbig[i].doubleValue();
            end[i] = endbig[i].doubleValue();
        }
        anim.setData(start, end);

        anim.setPoints((Point2D.Double)startData.get("start"), (Point2D.Double)endData.get("start"));
        anim.setFrameCount(count);
        anim.setOutput(tOutputFolder.getText());

        // Link with the Generator from MainForm
        parentform.gen.setFormula((String)startData.get("formula"));
        parentform.initializeGenerator();
        anim.setGenerator(parentform.gen);

        // Event handling
        anim.addEventListener(new AnimationListener() {
            public void initialized(BeginEvent evt) {}
            public void stepOccured(StepEvent evt) {
                lProgress.setText(String.valueOf(evt.getProgress()) + " / " + String.valueOf(evt.getMaxIterations()));
                pbProgress.setValue(evt.getProgress());
            }
            public void finished(FinishEvent evt) {}
        });

        new Thread(anim, "Animation").start();
    }//GEN-LAST:event_bGenerateActionPerformed

    private void bSelectOutputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSelectOutputActionPerformed
        JFileChooser ch = new JFileChooser();
        ch.setCurrentDirectory(new File("."));
        ch.setDialogTitle("Wybierz katalog docelowy");
        ch.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        ch.setAcceptAllFileFilterUsed(false);

        int result = ch.showOpenDialog(this);

        if (result == JFileChooser.APPROVE_OPTION) {
            File f = ch.getSelectedFile();
            try {
                tOutputFolder.setText(f.getCanonicalPath());

                setButtonState();
            } catch (IOException e) {
                JOptionPane.showMessageDialog(this, "Nie można było znaleźć katalogu.", this.getTitle(), JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_bSelectOutputActionPerformed

    private void bAbortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAbortActionPerformed
        if (!anim.isRunning()) return;

        anim.abort();
    }//GEN-LAST:event_bAbortActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAbort;
    private javax.swing.JButton bGenerate;
    private javax.swing.JButton bLoad1;
    private javax.swing.JButton bLoad2;
    private javax.swing.JButton bSelectOutput;
    private javax.swing.JFileChooser fcDialog;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lData1;
    private javax.swing.JLabel lData2;
    private javax.swing.JLabel lProgress;
    private javax.swing.JProgressBar pbProgress;
    private javax.swing.JFormattedTextField tDuration;
    private javax.swing.JFormattedTextField tFramerate;
    private javax.swing.JTextField tOutputFolder;
    // End of variables declaration//GEN-END:variables

}
